
server:
  port: 8080
swagger:
  enable: true
spring:
  datasource:
    hikari:
      minimum-idle: 3
      max-lifetime: 30000
      maximum-pool-size: 10
      connection-test-query: SELECT 1
    name: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.233.127.220:3306/3DPreview?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: Mysql@Test01
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
websocket:
  port: 9000 #??
  url: /msg	#??url